spring:
  datasource:
    url: "jdbc:h2:mem:test"
    driver-class-name: "org.h2.Driver"
    username: "sa"
    password: "password"
  h2:
    console:
      enabled: true
  liquibase:
    enabled: off
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true